version: '3.9'
services:
  backend:
    build: ./backend
    container_name: resume-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: ./backend
    container_name: resume-worker
    command: celery -A workers.tasks worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    container_name: resume-redis
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    container_name: resume-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
